<a href="https://colab.research.google.com/github/AshikaAnand12/Main/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
'''
Python lists:
- No support for vectorized operations
- No fixed type
- For loops not efficient 

NumPy Arrays:
- Support vectorized operations (addition, multiplication)
- Fixed data type
- More efficient
- Code is cleaner
'''

'\nPython lists:\n- No support for vectorized operations\n- No fixed type\n- For loops not efficient \n\nNumPy Arrays:\n- Support vectorized operations (addition, multiplication)\n- Fixed data type\n- More efficient\n- Code is cleaner\n'

In [ ]:
''' 
Python list v/s NumPy Array
- Both are ordered, mutable, duplicate
- We can perform indexing, iterating and slicing on both

- List are built in data structure
- To use array, we need to import

- List can use elements of different data types
- We can add element to list by list.append(value)

- Arrays have elements of a single data type
- NumPy Arrays consume less memory (6 times less memory)

- NumPy arrays ust hold the address of the element
- List need to keep info such as: object type, reference count, object value and size for each element

- NumPy Arrays are faster : See multiplication example
- NumPy Arrays objects have fixed memory
'''
list1 = [1,2,3]
n = [i*5 for i in list1 ] 
print(n)

[5, 10, 15]


In [ ]:
''' Arrays are convenient to use '''
array = np.array([1,2,3])
print(array*5)

[ 5 10 15]


In [ ]:
#  Array Datatype
n = np.array([10,20,30,40,50])
print(n)

[10 20 30 40 50]


In [ ]:
# Index starts with 0
n[0]

10

In [ ]:
n[0]=20
print(n)

[20 20 30 40 50]


In [ ]:
n[0] = 21.5 #truncated
print(n)

[21 20 30 40 50]


In [ ]:
n.dtype

dtype('int64')

In [ ]:
# To convert integer to smaller integer and occupy less memory, change dtype
sn = np.array(n,dtype = np.int8)
sn

array([21, 20, 30, 40, 50], dtype=int8)

In [ ]:
# When values are float, it automatically sets dtype to float
f = np.array([2.3,4.5])
f.dtype

dtype('float64')

In [ ]:
# Multidimensional array
'''
One Dimensional array - Vector
Two Dimensional array - Matrix
More than 2 dimensional array - Tensor
'''
nums = np.array([[1,2,3],[4,5,6]])
nums

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
nums[0][0]

1

In [ ]:
# 2D array
nums.ndim

2

In [ ]:
# Create 3D array
m = np.array([[[1,2,3],[5,6,7]],[[7,8,9],[10,11,12]]])
m

array([[[ 1,  2,  3],
        [ 5,  6,  7]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
m[1][0][2]

9

In [ ]:
# Multi dimensional arrays can be created effortlessly 
m.ndim

3

In [ ]:
# Creating array from lists and Python structures

list1 = [1,2,3]
array1 = np.array(list1)

In [ ]:
#List of different types
list2 = [1,2.2,'1']
array2 = np.array(list2)

In [ ]:
# All elements in the list are compared to the largest datatype
print(array2)

['1' '2.2' '1']


In [ ]:
array2.dtype

dtype('<U32')

In [ ]:
# Array from tuples
# Works similar to list for tuple
tuple1 = (1,2,3)
arrayt1 = np.array(tuple1)

In [ ]:
arrayt1

array([1, 2, 3])

In [ ]:
# Array for multidimensional list
m1 = [[[1,2,3],[5,6,7]],[[7,8,9],[10,11,12]]]

In [ ]:
arraym1 = np.array(m1)

In [ ]:
arraym1

array([[[ 1,  2,  3],
        [ 5,  6,  7]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
# Intrinsic NumPy Array Creation
# with np.arange and np.linspace - create nD array with equally distributed data
# np.arange(end) - default starts with 0
n = np.arange(10)
n

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# np.arange(start,end)
n2 = np.arange(20,25)
n2

array([20, 21, 22, 23, 24])

In [ ]:
# np.arange(start,end, step)
n3 = np.arange(10,50,5)
n3

array([10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
# Linspace
a = np.linspace(10,20)
a

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [ ]:
a2 = np.linspace(10,20)
a2

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [ ]:
# np.linspace(start,end, number of points) 
a3 = np.linspace(10,20,5)
a3

array([10. , 12.5, 15. , 17.5, 20. ])

In [ ]:
# rand function
# Used to generate randomly distributed data
# random.rand(val1) - 1D array
r = np.random.rand(10)
r

array([0.51325008, 0.61203417, 0.15842125, 0.03452947, 0.98374535,
       0.11441267, 0.57698313, 0.95084775, 0.71632624, 0.98303948])

In [ ]:
r2 = np.random.rand(4,4)
r2

array([[0.2830354 , 0.47500098, 0.29358669, 0.76364666],
       [0.46557478, 0.7506771 , 0.83611745, 0.82139381],
       [0.92018895, 0.44653236, 0.57063278, 0.08575447],
       [0.75879653, 0.42002005, 0.66211348, 0.91371175]])

In [ ]:
# To populate random integer values
r3 = np.random.randint(10,50,5)
r3

array([12, 36, 35, 37, 44])

In [ ]:
# Create arrays filled with constant values
# Array of Zeros 
c = np.zeros(5)
c

array([0., 0., 0., 0., 0.])

In [ ]:
# 2D constant array
# Pass tuple into np.zeros()
c2 = np.zeros((5,4))
c2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
c3 = np.zeros([3,2,4,5])
c3

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [ ]:
# Array of ones
c3 = np.ones(4)
c3

array([1., 1., 1., 1.])

In [ ]:
c4 = np.ones((2,2))
c4

array([[1., 1.],
       [1., 1.]])

In [ ]:
# Integer 2D array of ones
c5 = np.ones((2,2), dtype=int)
c5

array([[1, 1],
       [1, 1]])

In [ ]:
# Fill function : Used to create 1D array
# Fill already exisitng array with singular values

fi = np.empty(5, dtype=int) # np.empty() creates an empty array 
fi

array([0, 0, 0, 0, 0])

In [ ]:
fi.fill(3)
fi

array([3, 3, 3, 3, 3])

In [ ]:
# Full function: Used to create both 1D and 2D array
# Full Function : np.full(array length, value in array)
fu = np.full(5,10)
fu

array([10, 10, 10, 10, 10])

In [ ]:
# Full function to create a 2D array: np.full((rows, colums), value in array)
fu2 = np.full((3,5),7)
fu2

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [ ]:
# Shape and Size of an array
n = np.array([[1,2],[3,5]])
n
# n is 2D array
# n has size of 4 (4 elements in the array)
# n has dtype: int
# n has a shape(2,2) i.e., rows and columns

s = np.arange(20)
s

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
s2 = np.linspace((1,2),(3,4))
s2

array([[1.        , 2.        ],
       [1.04081633, 2.04081633],
       [1.08163265, 2.08163265],
       [1.12244898, 2.12244898],
       [1.16326531, 2.16326531],
       [1.20408163, 2.20408163],
       [1.24489796, 2.24489796],
       [1.28571429, 2.28571429],
       [1.32653061, 2.32653061],
       [1.36734694, 2.36734694],
       [1.40816327, 2.40816327],
       [1.44897959, 2.44897959],
       [1.48979592, 2.48979592],
       [1.53061224, 2.53061224],
       [1.57142857, 2.57142857],
       [1.6122449 , 2.6122449 ],
       [1.65306122, 2.65306122],
       [1.69387755, 2.69387755],
       [1.73469388, 2.73469388],
       [1.7755102 , 2.7755102 ],
       [1.81632653, 2.81632653],
       [1.85714286, 2.85714286],
       [1.89795918, 2.89795918],
       [1.93877551, 2.93877551],
       [1.97959184, 2.97959184],
       [2.02040816, 3.02040816],
       [2.06122449, 3.06122449],
       [2.10204082, 3.10204082],
       [2.14285714, 3.14285714],
       [2.18367347, 3.18367347],
       [2.

In [ ]:
s3 = np.full((2,2,2),10)
s3

array([[[10, 10],
        [10, 10]],

       [[10, 10],
        [10, 10]]])

In [ ]:
# Array has only 1D
np.shape(s)

(20,)

In [ ]:
np.shape(s2)

(50, 2)

In [ ]:
np.shape(s3)

(2, 2, 2)

In [ ]:
np.size(s)

20

In [ ]:
np.size(s2)

100

In [ ]:
np.size(s3)

8

In [ ]:
# Inserting/Adding/Appending, removing and sorting elements in array
i = np.array([1,2,3,5])
i

array([1, 2, 3, 5])

In [ ]:
# Insert : np.insert(array, index,value to be inserted)
i = np.insert(i,3,4)
i

array([1, 2, 3, 4, 5])

In [ ]:
i = np.append(i,6)
i

array([1, 2, 3, 4, 5, 6])

In [ ]:
# Delete: np.delete(array,index)
i = np.delete(i,4)
i

array([1, 2, 3, 4, 6])

In [ ]:
# Sorting array
i2 = np.random.randint(0,20,6)
i2

array([14,  1, 10,  5,  1, 16])

In [ ]:
print(np.sort(i2))

[ 1  1  5 10 14 16]


In [ ]:
i3 = np.array([[1,4,5,3,2],[5,0,3,1,2]])
i3

array([[1, 4, 5, 3, 2],
       [5, 0, 3, 1, 2]])

In [ ]:
print(np.sort(i3))

[[1 2 3 4 5]
 [0 1 2 3 5]]


In [ ]:
# Sorting an array of string
i4 = np.array(['Z','a','AQ','X','p','P','A','!'])
i4

array(['Z', 'a', 'AQ', 'X', 'p', 'P', 'A', '!'], dtype='<U2')

In [ ]:
print(np.sort(i4))

['!' 'A' 'AQ' 'P' 'X' 'Z' 'a' 'p']


In [ ]:
# Copies and views
x = np.array([1,2,3])
x

array([1, 2, 3])

In [ ]:
y=x
print(id(x))
print(id(y))

140008382550304
140008382550304


In [ ]:
y[1] = 3

In [ ]:
x

array([1, 3, 3])

In [ ]:
# creates a completely new array and copies the values : Deep copy
z = x.copy()

In [ ]:
z[1] = 5

In [ ]:
z

array([1, 5, 3])

In [ ]:
x

array([1, 3, 3])

In [ ]:
# View doesn't own the data, just presents the data with a different view
view = x.view()
view[0] = 10
print(view)
print(x)

[10  3  3]
[10  3  3]


In [ ]:
# Reshaping arrays - change shape of the data while data is retained
r = np.arange(1,13)
r

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
# Converting 1D array of 12 elements to 2 X 2 X 3 3D array
r2 = np.reshape(r,[2,2,3])
print(r2)
print('Dimension:',r2.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Dimension: 3


In [ ]:
# Converting 1D array to 2D array of size 6 X 2
r3 = np.reshape(r,(6,2)) # can also be written as np.reshape(r,[6,2]) : tuple and list accepted
r3

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [ ]:
# Flattening : Reducing n-dimesnional array to 1D array
r4 = np.reshape(r2,-1)
r4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
# 2 other functions for flattening: flatten and ravel
# Flatten will create a copy of the given array
# Raven will flatten the given array. Ay changes to the raven array will make changes to the original array
# NOTE : its array.flatten() : NOT np.flatten
r5 = r2.flatten()
r5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
r6 = r2.ravel()
r6

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
r5[0] = 10
r6[0] = 20
print(r5)
print(r6)
print(r2)

[10  2  3  4  5  6  7  8  9 10 11 12]
[20  2  3  4  5  6  7  8  9 10 11 12]
[[[20  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
# Indexing and Slicing
si = np.reshape(np.arange(1,13),[3,4])
si

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
si[1,1]

6

In [ ]:
si[1]

array([5, 6, 7, 8])

In [ ]:
si2 = np.reshape(si, [2,2,3])
si2

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
si2[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
si2[1,1]

array([10, 11, 12])

In [ ]:
si2[1,1,1]

11

In [ ]:
si2[1,-1,-1]

12

In [ ]:
si3 = np.arange(0,10)
si3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Slice : array[start:stop)
si4 = si3[2:6]
print(si4)
si5 = si3[:5]
print(si5)
si6 = si3[::2]
print(si6)
si7 = si3[-3:] # From last-3 element to last element
print(si7)

[2 3 4 5]
[0 1 2 3 4]
[0 2 4 6 8]
[7 8 9]


In [ ]:
# Slice 2D array
si8 = si2[1:,1:]
print(si8)
si9 = si2[1:]
print(si9)
si1 = si2[:1,:1,:1]
print(si1)

[[[10 11 12]]]
[[[ 7  8  9]
  [10 11 12]]]


In [ ]:
# Joining and Splitting
# 1. stack   2. vstack     3. concatenate      4. hstack

[[[1]]]


In [ ]:
# Concatenate 1D array
arr = np.arange(0,10)
arr2 = np.arange(10,20)
arr3 = np.concatenate([arr,arr2])
print(arr3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
# Concatenate 2D array over y axis:
arr1 = np.reshape(np.arange(12),(3,4))
arr2 = np.reshape(np.arange(12,24),[3,4])
arr3 = np.concatenate((arr1,arr2), axis = 1) # check without axis
print(arr3)
print(arr1)

[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# Concatentate with stack. :works like a stack
# Notice all the shapes in the arguments are tuples or list : stack(()) concatenate(())
stack_arr = np.stack((arr1,arr2))
stack_arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
# Concatenate with hstack: horizontal stacking : Similar to concatenating on axis = 1
harr = np.hstack((arr1,arr2))
harr 

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
# Concatenate with vstack: Vertical stacking : : Similar to concatenating without axis (axis = 0)
varr = np.vstack((arr1,arr2))
varr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# Splitting arrays
# Splitting into multiple arrays
# Functions: 1. split   2. array_split   3. hsplit   4. vsplit

# array_split
split_arr = np.array_split(si3 ,5) # Array split can split array into specified number of parts
split_arr   

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [ ]:
split_arr[0]

array([0, 1])

In [ ]:
arr5 = np.array_split(si3,8)
arr5

[array([0, 1]),
 array([2, 3]),
 array([4]),
 array([5]),
 array([6]),
 array([7]),
 array([8]),
 array([9])]

In [ ]:
hs_arr = np.hsplit(arr1,2) # Try 4
hs_arr

[array([[0, 1],
        [4, 5],
        [8, 9]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [ ]:
arr1 = np.reshape(np.arange(12),(3,4))
vs_arr = np.vsplit(arr1,3)
vs_arr

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [ ]:
# Arithematic functions
# Vectorization
a = np.arange(1,11)
b = np.arange(21,31)
print(a+b)
print(a-b)
print(a*b)
print(b/a)
print(a**2)
print(a*2)
print(a%2)

[22 24 26 28 30 32 34 36 38 40]
[-20 -20 -20 -20 -20 -20 -20 -20 -20 -20]
[ 21  44  69  96 125 156 189 224 261 300]
[21.         11.          7.66666667  6.          5.          4.33333333
  3.85714286  3.5         3.22222222  3.        ]
[  1   4   9  16  25  36  49  64  81 100]
[ 2  4  6  8 10 12 14 16 18 20]
[1 0 1 0 1 0 1 0 1 0]


In [ ]:
c = np.add(a,b) #subtract, multiply, divide, mod, power, sqrt
print(c)

[22 24 26 28 30 32 34 36 38 40]


In [ ]:
# Broadcasting
# We need to apply arithmetic operations on arrays with different shapes : Broadcasting
# Smaller array is broadcast across larger array so that they have compatible shapes
# (3,3) + (1,3)  = (3,3) - (1,3) array is converted to (3,3) by copying the 1st row into all 3 columns
# Dimensions are compatible if their axes on a 1-1 basis, they have either the same length or length of one

a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
b = np.arange(1,4)
b

array([1, 2, 3])

In [ ]:
a+b

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [ ]:
a = np.array([[ 0,  0,  0], [10, 10, 10], [20, 20, 20], [30, 30, 30]])
b = np.array([1.0, 2.0, 3.0])
print(a + b)

[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [ ]:
c = np.arange(1,3)
c
# a+c # Dimensions are not compatible # Uncomment a+c

array([1, 2])

In [ ]:
# Broadcating on 3D array
d = np.arange(0,12).reshape(2,2,3)
d

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [ ]:
e = np.arange(3)
e

array([0, 1, 2])

In [ ]:
d-e

array([[[0, 0, 0],
        [3, 3, 3]],

       [[6, 6, 6],
        [9, 9, 9]]])

In [ ]:
# Aggregate functions
p = np.arange(10,110,10)
q = np.arange(10,100,10).reshape(3,3)
r = np.arange(10,110,10).reshape(2,5)
print("P:",p)
print("Q:",q)
print("R:",r)

P: [ 10  20  30  40  50  60  70  80  90 100]
Q: [[10 20 30]
 [40 50 60]
 [70 80 90]]
R: [[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [ ]:
p.sum()

550

In [ ]:
q.sum(axis=0)

array([120, 150, 180])

In [ ]:
r.prod(axis = 0)

array([ 600, 1400, 2400, 3600, 5000])

In [ ]:
np.average(p) #q,r

55.0

In [ ]:
np.min(q) #p,r

10

In [ ]:
np.max(r) #p,q

100

In [ ]:
# mean or average
np.mean(p) #q,r

55.0

In [ ]:
# Standard deviation
np.std(q) #p,r

25.81988897471611

In [ ]:
#Unique items and counts
u = np.random.randint(0,10,14)
u

array([0, 2, 1, 2, 6, 0, 8, 2, 6, 6, 0, 1, 7, 4])

In [ ]:
np.unique(u)

array([0, 1, 2, 4, 6, 7, 8])

In [ ]:
v = np.random.randint(0,10,16).reshape(4,4)
v

array([[5, 4, 3, 9],
       [1, 0, 7, 5],
       [7, 8, 1, 5],
       [2, 7, 1, 8]])

In [ ]:
np.unique(v)

array([0, 1, 2, 3, 4, 5, 7, 8, 9])

In [ ]:
v = np.array([[1,1,2,1],[3,1,2,1],[1,1,2,1],[7,1,1,1]])
print(v)
np.unique(v,axis=0) #axis =1

[[1 1 2 1]
 [3 1 2 1]
 [1 1 2 1]
 [7 1 1 1]]


array([[1, 1, 2, 1],
       [3, 1, 2, 1],
       [7, 1, 1, 1]])

In [ ]:
# Get indices of unique elements 
np.unique(u, return_index=True)

(array([0, 1, 2, 4, 6, 7, 8]), array([ 0,  2,  1, 13,  4, 12,  6]))

In [ ]:
# Number of times 0 occured in the array
np.unique(u, return_counts=True)

(array([0, 1, 2, 4, 6, 7, 8]), array([3, 2, 3, 1, 3, 1, 1]))

In [ ]:
# Transpose : move axis and swap axis
# converts rows to columns and columns to rows
v = np.random.randint(0,10,12).reshape(3,4)
v

array([[9, 9, 9, 2],
       [2, 2, 0, 9],
       [9, 6, 6, 2]])

In [ ]:
np.transpose(v)

array([[9, 2, 9],
       [9, 2, 6],
       [9, 0, 6],
       [2, 9, 2]])

In [ ]:
np.transpose(v, (1,0))

array([[9, 2, 9],
       [9, 2, 6],
       [9, 0, 6],
       [2, 9, 2]])

In [ ]:
# Moveaxis and swapaxis
w = np.reshape(np.arange(12),[2,2,3])
print(w)
np.moveaxis(w,0,-1)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


array([[[ 0,  6],
        [ 1,  7],
        [ 2,  8]],

       [[ 3,  9],
        [ 4, 10],
        [ 5, 11]]])

In [ ]:
np.swapaxes(w,0,2)

array([[[ 0,  6],
        [ 3,  9]],

       [[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]]])

In [ ]:
# Reverse an array
u[::-1]

array([4, 7, 1, 0, 6, 6, 2, 8, 0, 6, 2, 1, 2, 0])

In [ ]:
np.flip(u)

array([4, 7, 1, 0, 6, 6, 2, 8, 0, 6, 2, 1, 2, 0])

In [ ]:
w = np.reshape(np.arange(9),[3,3])
w

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.flip(w)

array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])

In [ ]:
np.flip(w,1)

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])