<a href="https://colab.research.google.com/github/AshikaAnand12/Main/blob/main/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# pytorch operations
import torch
import numpy as np

In [ ]:
a1 = torch.ones(3)
print(a1)

tensor([1., 1., 1.])


In [ ]:
print(float(a1[1]))

1.0


In [ ]:
a1[2] = 5
print(a1)

tensor([1., 1., 5.])


In [ ]:
# 2D tensor
arr = torch.tensor([[2,3],[4,5],[8,9]])
print("Array: ",arr)
# print("Size: ", torch.Size([3,2]))
print("Shape: ", arr.shape)

Array:  tensor([[2, 3],
        [4, 5],
        [8, 9]])
Shape:  torch.Size([3, 2])


In [ ]:
zer = torch.zeros([2,3,4])
print("Array looks like:",zer)
print("Shape: ", zer.shape)
print("Size: ",zer.size())

Array looks like: tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape:  torch.Size([2, 3, 4])
Size:  torch.Size([2, 3, 4])


In [ ]:
torch.zeros([2, 4], dtype=torch.int32)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

In [ ]:
!nvidia-smi

Thu Feb 24 04:05:59 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   31C    P8    28W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
torch.cuda.is_available()

True

In [ ]:
# To use CUDA
cuda0 = torch.device('cuda:0')
torch.ones([2, 4], dtype=torch.float64, device=cuda0)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0', dtype=torch.float64)

In [ ]:
# You can access the storage for a given tensor by using the .storage property
arr2 = torch.tensor([[2.0,5.5,3.3],[2,3,5],[3,3,3],[5.5,5.5,5.5]])
arr2.storage()
print(arr2)


tensor([[2.0000, 5.5000, 3.3000],
        [2.0000, 3.0000, 5.0000],
        [3.0000, 3.0000, 3.0000],
        [5.5000, 5.5000, 5.5000]])


In [ ]:
arr2[0]

tensor([2.0000, 5.5000, 3.3000])

In [ ]:
arr2.storage()[1]

5.5

In [ ]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
print(second_point)
second_point.storage_offset()

tensor([5., 3.])


2

In [ ]:
# Cloning a tensor
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [ ]:
# Transpose view
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [ ]:
# IDs of points and transpose of points is same, only view has changed
id(points.storage()) == id(points_t.storage())

True

In [ ]:
print(points.shape)
print(points_t.shape)

torch.Size([3, 2])
torch.Size([2, 3])


In [ ]:
one_t = torch.ones(3, 4, 5)
transpose_t = one_t.transpose(0, 2)
print(one_t)
print(transpose_t)
one_t.shape

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])
tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])


torch.Size([3, 4, 5])

In [ ]:
# Stride example: https://zhang-yang.medium.com/explain-pytorch-tensor-stride-and-tensor-storage-with-code-examples-50e637f1076d
x = torch.arange(12).view((3,4))
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [ ]:
# Stride is a tuple indicating the number of elements in the storage that have to be skipped when the index is increased by 1 in each dimension
stride = x.stride()
stride

(4, 1)

In [ ]:
# To get value at x[2][1]
'''Here comes the part that explains stride. 
Suppose you want to access the element of the tensor x at row-2 and column-1, whose value is 9. 
We can write this in code. Note that idx are the indices of the element being accessed.'''
idx = (2, 1)
item = x[idx].item()
item

9

In [ ]:
# Equivalent to the previous cell
loc = idx[0]*stride[0] + idx[1]*stride[1]
loc

9

In [ ]:
# Generally
loc = sum([i*s for i,s in zip(idx, stride)])
loc

9

In [ ]:
''' Contiguous: Returns a contiguous in memory tensor containing the same data as self tensor. 
If self tensor is already in the specified memory format, this function returns the self tensor. '''
print(points.is_contiguous())
print(points_t.is_contiguous())

True
False


In [ ]:
# Different data types
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)
print("Double DataType: ",double_points)
print("Short DataType: ",short_points)

Double DataType:  tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)
Short DataType:  tensor([[1, 2],
        [3, 4]], dtype=torch.int16)


In [ ]:
# Typecasting
double_points = torch.zeros(10, 2).double() # Can also be written as .to(torch.double)
short_points = torch.ones(10, 2).short()

In [ ]:
# Random Initialization
tens = torch.randn(10,2) # 10, 2D array whose value is between 0-1
print(tens)

tensor([[-1.1681,  0.2643],
        [ 0.4563, -0.3781],
        [-0.4220, -0.6726],
        [-0.0180,  0.3261],
        [-0.7610, -0.9417],
        [ 0.2582, -0.5313],
        [-0.0597, -0.7191],
        [ 0.9988, -0.9465],
        [-0.1074,  0.3311],
        [ 0.5154,  1.3582]])


In [ ]:
# Broadcasting
x = torch.ones(3,2,4)
y = torch.ones(3,2,4)
print(x+y)
print((x+y).size())

tensor([[[2., 2., 2., 2.],
         [2., 2., 2., 2.]],

        [[2., 2., 2., 2.],
         [2., 2., 2., 2.]],

        [[2., 2., 2., 2.],
         [2., 2., 2., 2.]]])
torch.Size([3, 2, 4])


In [ ]:
x = torch.ones(3,2,4)
y = torch.ones(2,4)
print(x+y)
print((x+y).size())

tensor([[[2., 2., 2., 2.],
         [2., 2., 2., 2.]],

        [[2., 2., 2., 2.],
         [2., 2., 2., 2.]],

        [[2., 2., 2., 2.],
         [2., 2., 2., 2.]]])
torch.Size([3, 2, 4])


In [ ]:
# Named tensors
x = torch.zeros(2,3,names=('rows','columns'))
x

tensor([[0., 0., 0.],
        [0., 0., 0.]], names=('rows', 'columns'))

In [ ]:
y = x.rename(rows = 'Rows')
y

tensor([[0., 0., 0.],
        [0., 0., 0.]], names=('Rows', 'columns'))

In [ ]:
# Matrix multiplication
t1 = torch.randn(3,5) * 10
t2 = torch.randn(5,3) * 10
print(t1)
print(t2)
print(torch.matmul(t1,t2))

tensor([[-14.5930,   8.0915,   3.5935,   4.2028,  -4.9383],
        [ -6.0198,  -0.2768,  -2.8306,   6.5161,   2.2366],
        [ -5.0220, -11.4222,  13.1325,  -2.3110, -20.2467]])
tensor([[ -3.7085,   7.4405,   4.0615],
        [ -8.2074,   6.6774, -16.1681],
        [ -2.9461,  -0.8994,  -5.8619],
        [ 13.1821,  -4.7818,  -6.5008],
        [-10.7932,  -6.3255,  -0.9603]])
tensor([[  85.8235,  -46.6406, -233.7383],
        [  94.6911,  -89.3995,  -47.8882],
        [ 261.7440,   13.6748,  121.7633]])


### Einsum

In [ ]:
# Transpose
a = torch.arange(6).reshape(2, 3)
print("A: ",a)
torch.einsum('ij->ji', [a])

A:  tensor([[0, 1, 2],
        [3, 4, 5]])


tensor([[0, 3],
        [1, 4],
        [2, 5]])

In [ ]:
# Sum of all values in the matrix
torch.einsum('ij->', [a])

tensor(15)

In [ ]:
# Sum of all values in all column of the matrix
torch.einsum('ij->j', [a])

tensor([3, 5, 7])

In [ ]:
# Sum of all values in all rows of the matrix
torch.einsum('ij->i', [a])

tensor([ 3, 12])

In [ ]:
# Matrix vector multiplication - Regular matrix multiplication (No need for second matrix to transpose)
b = torch.arange(3)
print(a)
print(b)
torch.einsum('ik,k->i', [a, b]) # (2X3)X(3X1) = (2X1)

tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([0, 1, 2])


tensor([ 5, 14])

In [ ]:
# 2D matrix multiplication 
a = torch.arange(6).reshape(2, 3)
b = torch.arange(15).reshape(3, 5)
print(torch.einsum('ik,kj->ij', [a, b]))
print(torch.matmul(a,b))

tensor([[ 25,  28,  31,  34,  37],
        [ 70,  82,  94, 106, 118]])
tensor([[ 25,  28,  31,  34,  37],
        [ 70,  82,  94, 106, 118]])


In [ ]:
# DOT product
a = torch.arange(3)     # -- a: vector of length 3 containing [0, 1, 2]
b = torch.arange(3,6)   # -- b: vector of length 3 containing [3, 4, 5]
print(torch.einsum('i,i->', [a, b])) # (0*3)+(1*4)+(5*2)
print(torch.dot(a,b))

tensor(14)
tensor(14)


In [ ]:
# HADAMARD PRODUCT
a = torch.arange(6).reshape(2, 3)
b = torch.arange(6,12).reshape(2, 3)
print(a)
print(b)
print(torch.einsum('ij,ij->ij', [a, b]))
print(a*b)

tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[ 6,  7,  8],
        [ 9, 10, 11]])
tensor([[ 0,  7, 16],
        [27, 40, 55]])
tensor([[ 0,  7, 16],
        [27, 40, 55]])


In [ ]:
# Outer product
a = torch.arange(3)
b = torch.arange(3,7)  # -- a vector of length 4 containing [3, 4, 5, 6]
print(a)
print(b)
print(torch.einsum('i,j->ij', [a, b]))
print(torch.ger(a,b))

tensor([0, 1, 2])
tensor([3, 4, 5, 6])
tensor([[ 0,  0,  0,  0],
        [ 3,  4,  5,  6],
        [ 6,  8, 10, 12]])
tensor([[ 0,  0,  0,  0],
        [ 3,  4,  5,  6],
        [ 6,  8, 10, 12]])


In [ ]:
# Batch Matrix Multiplication
a = torch.randn(3,2,5)
b = torch.randn(3,5,3)
print(a)
print(b)
print(torch.einsum('ijk,ikl->ijl', [a, b]))
print(torch.bmm(a,b))

tensor([[[ 1.5158,  2.3045,  0.5048,  1.4461,  1.2550],
         [ 0.7375, -2.6923, -1.3704, -0.4043, -1.4620]],

        [[-0.5269,  1.0985,  0.9800, -0.7948,  1.7089],
         [-1.5985,  0.2092, -0.0551,  2.3682,  0.1505]],

        [[ 1.0826,  0.7265,  0.1437,  2.5787,  0.2504],
         [-0.9803,  0.1184, -0.8868, -0.3849, -0.0944]]])
tensor([[[ 0.3481,  0.5353, -1.4027],
         [ 0.3937, -0.2770,  0.4656],
         [ 0.6304, -0.5168,  0.0263],
         [ 0.3980,  1.0180,  0.0382],
         [-1.0523, -1.5134,  0.6494]],

        [[ 0.5052,  1.2546, -1.6933],
         [ 0.9788, -0.6731,  1.0471],
         [ 0.9191, -1.9851, -0.2188],
         [ 0.4296, -0.5518, -0.1745],
         [-0.8272, -2.2703,  0.3589]],

        [[-0.8504,  0.5176, -0.2650],
         [ 0.5245,  0.3778, -0.4943],
         [-0.1178, -0.9145,  0.7978],
         [-0.0092, -0.6454, -0.4488],
         [ 0.0068,  0.7553, -1.7950]]])


tensor([[[ 1.0079, -0.5151, -0.1695],
         [-0.2894,  3.6500, -3.2890]],

        [[-0.0453, -6.7871,  2.5801],
         [ 0.2394, -3.6852,  2.5785]],

        [[-0.5786, -0.7718, -2.1383],
         [ 1.0030,  0.5255, -0.1641]]])

In [ ]:
# Tensor Contraction
a = torch.randn(2,3,5,7)
b = torch.randn(11,13,3,17,5)
torch.einsum('pqrs,tuqvr->pst', [a, b]) #Change pst to pstu,pstuv... and test

tensor([[[  50.0475,   24.3400,   22.8494,   11.7058,   14.6462,  -60.7501,
             1.1200,    1.9720,  -40.6161,  -92.1696,   11.9068],
         [ -62.7750,  -24.4923,   32.1977,  -63.4768,   22.0814,  -43.7728,
            27.1874,   14.1574,   29.1888,   94.6570,   26.0478],
         [ -24.7593, -109.6854,   53.8858,  -26.2571,  -80.6565,  130.0378,
           -39.6676,  113.5811,   65.6690,    2.9302,   -1.7818],
         [  34.5109,    1.8121,   86.4162,  -33.8272,    3.4089,   43.1397,
           -91.5289,  -29.4734,    7.9893,  -36.6308,   -1.0183],
         [ -27.0221,  -17.0977,  -76.9605,  -48.5294,  -46.6143,   43.5913,
           -30.3892,    5.1924,   10.0819,  113.3814,   78.5701],
         [  39.0595,   10.9674, -157.9719,  -57.1692,  -24.0597,   43.6933,
          -114.2538,  -77.2655,   74.8693, -110.9970,   82.7980],
         [-124.8004, -117.7841,  -68.6979,   33.1127,  -28.4969,   29.6455,
           -40.6118,   31.2820,   12.6646,  -17.9418,   38.8668]],

    

In [ ]:
# Bilinear transformation
a = torch.randn(2,3)
b = torch.randn(5,3,7)
c = torch.randn(2,7)
torch.einsum('ik,jkl,il->ij', [a, b, c])

tensor([[-1.4793,  0.0967,  0.1389, -2.3219,  1.0196],
        [ 4.7391, -0.5521, -0.9015,  1.8890,  2.7373]])

In [ ]:
# Element wise squaring
a=torch.arange(6).reshape(2,3)
print(a)
print(torch.einsum('ij,ij->ij',a,a))
print(a**2)

tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[ 0,  1,  4],
        [ 9, 16, 25]])
tensor([[ 0,  1,  4],
        [ 9, 16, 25]])


In [ ]:
# Sum of main diagonal
a=torch.arange(4).reshape(2,2)
print(a)
print(torch.einsum('ii->',a))
print(torch.trace(a))

tensor([[0, 1],
        [2, 3]])
tensor(3)
tensor(3)


In [ ]:
# Sum along axis 0
a=torch.arange(6).reshape(2,3)
print(a)
print(torch.einsum('ij->j',a))
print(torch.sum(a,0))

tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([3, 5, 7])
tensor([3, 5, 7])


In [ ]:
# Sum along axis 1
a=torch.arange(6).reshape(2,3)
print(a)
print(torch.einsum('ij->i',a))
print(torch.sum(a,1))

tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([ 3, 12])
tensor([ 3, 12])


In [ ]:
# Sum over multiple axis
a = torch.randn((3,5,4,7,6))
print(a.shape)
print(torch.einsum('ijklm->',a))
print(torch.sum(a, dim = (0,1,2,3,4)))

torch.Size([3, 5, 4, 7, 6])
tensor(-23.6154)
tensor(-23.6154)


In [ ]:
a = torch.randn((3,5,4,7,6))
print(a.shape)
print(torch.einsum('ijklm->k',a))
print(torch.sum(a, dim = (0,1,3,4)))

torch.Size([3, 5, 4, 7, 6])
tensor([-33.2010,   1.5513,  34.6175,  48.4488])
tensor([-33.2010,   1.5513,  34.6175,  48.4488])
