<a href="https://colab.research.google.com/github/AshikaAnand12/Main/blob/main/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Tensor is a container for data — usually numerical data
# 0D - Scalar, 1D - vector, 2D - matrix, 3D - tensor, 
import tensorflow as tf
import numpy as np

### Tensor Vocabulary 

In [ ]:
# Tensor vocabulary: Shape, Size, Rank, Axis/Dimension
t1 = tf.zeros([3,2,4,5])
print(t1)

tf.Tensor(
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]], shape=(3, 2, 4, 5), dtype=float32)


In [ ]:
print("Number of Axes: ",t1.ndim)
print("Type of every element: ",t1.dtype)
print("Total number of elements: ", tf.size(t1))

Number of Axes:  4
Type of every element:  <dtype: 'float32'>
Total number of elements:  tf.Tensor(120, shape=(), dtype=int32)


In [ ]:
# Creating array of constants
t2 = tf.constant([1,2,3,4,5,6])
print(t2)

tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)


In [ ]:
t3 = tf.constant([[1,2],[8,9],[6,3],[20,100],[5,5]])
print(t3)

tf.Tensor(
[[  1   2]
 [  8   9]
 [  6   3]
 [ 20 100]
 [  5   5]], shape=(5, 2), dtype=int32)


In [ ]:
t3[0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [ ]:
t3[0].numpy()

array([1, 2], dtype=int32)

In [ ]:
print(t3.dtype)
print(t3.shape)

<dtype: 'int32'>
(5, 2)


In [ ]:
print(tf.zeros(shape=(2,2,3)))

tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]], shape=(2, 2, 3), dtype=float32)


## Tensor Array 

In [ ]:
ta = tf.TensorArray(tf.int32, size=0, dynamic_size=True, clear_after_read=False)
ta = ta.write(0, 10)
ta = ta.write(1, 20)
ta = ta.write(2, 30)

In [ ]:
# Memory Location of tensor array is printed
print(ta)

In [ ]:
# To read value at single index
ta.read(0)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [ ]:
# To read the entire array
ta.stack()

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 20, 30], dtype=int32)>

In [ ]:
# Create 2D array
t4 = tf.TensorArray(tf.int32, size=3)

In [ ]:
# Write into 2D array
t4 = t4.write(0, tf.constant([1, 2]))
t4 = t4.write(1, tf.constant([3, 4]))
t4 = t4.write(2, tf.constant([5, 6]))

In [ ]:
# Read 2D array
t4.stack()

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

Sparse tensor

In [ ]:
# Sparse tensors store values by index in a memory-efficient manner
sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]],
                                       values=[1, 2],
                                       dense_shape=[3, 4])
print(sparse_tensor, "\n")

# You can convert sparse tensors to dense
print(tf.sparse.to_dense(sparse_tensor))

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64)) 

tf.Tensor(
[[1 0 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)


### Indexing

In [ ]:
#Single axis tensor
t6 = tf.constant([1,2,3,4,5,6,7,8,9])
print(t6)

tf.Tensor([1 2 3 4 5 6 7 8 9], shape=(9,), dtype=int32)


In [ ]:
# Multiple axis tensor
t5 = tf.constant([[1,2],[2,3],[3,4]])
print(t5.numpy())

[[1 2]
 [2 3]
 [3 4]]


In [ ]:
# Read a value in multishape tensor
print(t5[1, 1].numpy())

3


In [ ]:
# Slicing
print("Everything:", t6[:].numpy())
print("Before 4:", t6[:4].numpy())
print("From 4 to the end:", t6[4:].numpy())
print("From 2, before 7:", t6[2:7].numpy())
print("Every other item:", t6[::2].numpy())
print("Reversed:", t6[::-1].numpy())
print("Second row/Skip first row:", t5[1, :].numpy())
print("Second column:", t5[:, 1].numpy())
print("Last row:", t5[-1, :].numpy())
print("First item in last column:", t5[0, -1].numpy())

Everything: [1 2 3 4 5 6 7 8 9]
Before 4: [1 2 3 4]
From 4 to the end: [5 6 7 8 9]
From 2, before 7: [3 4 5 6 7]
Every other item: [1 3 5 7 9]
Reversed: [9 8 7 6 5 4 3 2 1]
Second row/Skip first row: [2 3]
Second column: [2 3 4]
Last row: [3 4]
First item in last column: 2


### Reshaping

In [ ]:
# Convert tensor object to python list
print(t5.shape.as_list())

[3, 2]


In [ ]:
# Reshape tensor
t5 = tf.reshape(t5,[2,3])

In [ ]:
print(t5)

tf.Tensor(
[[1 2 2]
 [3 3 4]], shape=(2, 3), dtype=int32)


In [ ]:
# Flatten a tensor
t5 = tf.reshape(t5,-1)
print(t5)

tf.Tensor([1 2 2 3 3 4], shape=(6,), dtype=int32)


In [ ]:
ragged = [
    [0, 1, 2, 3],
    [4, 5],
    [6, 7, 8],
    [9]]

In [ ]:
ragged_tensor = tf.ragged.constant(ragged)
print(ragged_tensor)

<tf.RaggedTensor [[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]]>


In [ ]:
print(ragged_tensor.shape)

(4, None)


## Tensor Variables

In [ ]:
my_tensor = tf.constant([[1.0, 2.0], [3.0, 4.0]])
num_variable = tf.Variable(my_tensor)

# Variables can be all kinds of types, just like tensors
bool_variable = tf.Variable([False, False, False, True])
complex_variable = tf.Variable([5 + 4j, 6 + 1j])

In [ ]:
print("Shape: ", num_variable.shape)
print("DType: ", num_variable.dtype)
print("As NumPy: ", num_variable.numpy())

Shape:  (2, 2)
DType:  <dtype: 'float32'>
As NumPy:  [[1. 2.]
 [3. 4.]]


In [ ]:
print("Shape: ", bool_variable.shape)
print("DType: ", num_variable.dtype)
print("As NumPy: ", num_variable.numpy())

Shape:  (4,)
DType:  <dtype: 'float32'>
As NumPy:  [[1. 2.]
 [3. 4.]]


In [ ]:
print("Shape: ", complex_variable.shape)
print("DType: ", complex_variable.dtype)
print("As NumPy: ", complex_variable.numpy())

Shape:  (2,)
DType:  <dtype: 'complex128'>
As NumPy:  [5.+4.j 6.+1.j]


In [ ]:
print("A variable:", num_variable)
print("\nViewed as a tensor:", tf.convert_to_tensor(num_variable))
print("\nIndex of highest value:", tf.argmax(num_variable))

# This creates a new tensor; it does not reshape the variable.
print("\nCopying and Reshaping: ", tf.reshape(num_variable, [1,4]))

A variable: <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

Viewed as a tensor: tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)

Index of highest value: tf.Tensor([1 1], shape=(2,), dtype=int64)

Copying and Reshaping:  tf.Tensor([[1. 2. 3. 4.]], shape=(1, 4), dtype=float32)


In [ ]:
a = tf.Variable([2.0, 3.0])

# Create b based on the value of a
b = tf.Variable(a)
a.assign([5, 6])

# a and b are different
print("a: ",a.numpy())
print("\n b:",b.numpy())

# There are other versions of assign
print("\n Added value to 'a' variable: ",a.assign_add([2,3]).numpy())  # Adding values of a by list in add([])
print("\n Subtract value from 'a' variable: ",a.assign_sub([2,2]).numpy())  # Subtracting values of a by list in add([])

a:  [5. 6.]

 b: [2. 3.]

 Added value to 'a' variable:  [7. 9.]

 Subtract value from 'a' variable:  [5. 7.]


In [ ]:
# Create a and b; they will have the same name but will be backed by
# different tensors.
t = tf.constant([[1.0, 2.0], [3.0, 4.0]])
a = tf.Variable(t, name="id1")
# A new variable with the same name, but different value
# Note that the scalar add is broadcast
b = tf.Variable(t+1, name="id1")

# These are elementwise-unequal, despite having the same name
print(a == b)
print(a,b)

tf.Tensor(
[[False False]
 [False False]], shape=(2, 2), dtype=bool)
<tf.Variable 'id1:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)> <tf.Variable 'id1:0' shape=(2, 2) dtype=float32, numpy=
array([[2., 3.],
       [4., 5.]], dtype=float32)>


In [ ]:
# Math with tensorflow
a = tf.random.normal(shape=(2,2))*10
a = tf.cast(a, tf.int32)
b = tf.random.normal(shape=(2,2))*10
b = tf.cast(b, tf.int32)
c = a+b
d = tf.square(c)
# e = tf.exp(d) #Cannot do exp on int
print("a: ",a)
print("\nb: ",b)
print("\nSum: ",c)
print("\nSquare: ",d)
# print("\nExponent: ",e)

a:  tf.Tensor(
[[-2  0]
 [ 0 -7]], shape=(2, 2), dtype=int32)

b:  tf.Tensor(
[[ 3 12]
 [ 0 13]], shape=(2, 2), dtype=int32)

Sum:  tf.Tensor(
[[ 1 12]
 [ 0  6]], shape=(2, 2), dtype=int32)

Square:  tf.Tensor(
[[  1 144]
 [  0  36]], shape=(2, 2), dtype=int32)


In [ ]:
# Matrix Multiplication
with tf.compat.v1.Session() as ses:
  a = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])       # 2 X 3
  b = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])     # 3 X 2
  c = tf.matmul(a, b)        # Shape: (2 X 3) X (3 X 2) = ( 2 X 2 )
  print(ses.run(c))

[[22. 28.]
 [49. 64.]]


In [ ]:
# Matrix multiplication can also be written as:

a = tf.Variable([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
b = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
c = tf.Variable([[2.0, 2.0, 2.0], [2.0, 2.0, 2.0]])
d = tf.matmul(a, b)

print(d)

tf.Tensor(
[[22. 28.]
 [49. 64.]], shape=(2, 2), dtype=float32)


In [ ]:
# Element-wise multiplication
e = a*c
print(e)

tf.Tensor(
[[ 2.  4.  6.]
 [ 8. 10. 12.]], shape=(2, 3), dtype=float32)


## Tensorflow Einsum

In [ ]:
# Matrix Multiplication 
m1 = (tf.random.normal(shape=[2,3]) * 10)
m1 = tf.cast(m1, tf.int32)
m2 = (tf.random.normal(shape=[3,2]) * 10)
m2 = tf.cast(m2, tf.int32)
e = tf.einsum('ij,jk -> ik',m1,m2)
print(e)

tf.Tensor(
[[ 15 -55]
 [ 70 -75]], shape=(2, 2), dtype=int32)


In [ ]:
# Dot product
u = (tf.random.normal(shape=[5]) * 10)
v = (tf.random.normal(shape=[5]) * 10)
e = tf.einsum('i,i->',u,v) #u[i]*v[i]
print(e)

tf.Tensor(253.43874, shape=(), dtype=float32)


In [ ]:
# Outer product
u = (tf.random.normal(shape=[3]) * 10)
v = (tf.random.normal(shape=[5]) * 10)
e = tf.einsum('i,j->ij',u,v) #u[i]*v[i]
print(e)

tf.Tensor(
[[-10.998315 -40.052246  29.63393   17.688482  18.029322]
 [-24.708122 -89.97886   66.57372   39.737835  40.50354 ]
 [ 11.041921  40.21105  -29.751423 -17.758614 -18.100805]], shape=(3, 5), dtype=float32)


In [ ]:
# Transpose
e = tf.einsum('ij->ji',m1)
print(e)

tf.Tensor(
[[ -1  -9]
 [ 11  -8]
 [-27  13]], shape=(3, 2), dtype=int32)


In [ ]:
# Diagonal
m = tf.reshape(tf.range(9), [3,3])
diag = tf.einsum('ii->i', m)
print(m , diag, diag.shape)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32) tf.Tensor([0 4 8], shape=(3,), dtype=int32) (3,)


In [ ]:
# Repeated indices are summed
trace = tf.einsum('ii', m)  # output[j,i] = trace(m) = sum_i m[i, i]
assert trace == sum(diag)
print(m)
print("Trace: ",trace)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
Trace:  tf.Tensor(12, shape=(), dtype=int32)


In [ ]:
# Batch matrix multiplication 
s = tf.random.normal(shape=[4,1,3])
t = tf.random.normal(shape=[4,3,2])
e = tf.einsum('bij,bjk->bik', s, t)
# output[a,i,k] = sum_j s[a,i,j] * t[a, j, k]
print("s: ",s)
print("t: ",t)
print("e: ",e)
print("Shape: ",e.shape)

s:  tf.Tensor(
[[[-1.6360364  -0.5875084  -2.1128955 ]]

 [[-1.0677503  -0.26370835 -0.36680022]]

 [[ 0.4012148  -0.30533656 -0.04695938]]

 [[ 0.86225426 -0.06065151  1.8529147 ]]], shape=(4, 1, 3), dtype=float32)
t:  tf.Tensor(
[[[ 0.4721736  -0.24931516]
  [-1.1077102   0.30164889]
  [ 1.9044129   0.07856104]]

 [[-2.5674555   1.5218024 ]
  [ 0.16024436  1.5072573 ]
  [ 0.68749356  0.91875374]]

 [[-0.3491817   1.2699556 ]
  [ 0.32811418 -0.11639549]
  [-0.8374061   0.5327191 ]]

 [[ 1.1781172   0.40680742]
  [ 0.57684815 -0.47147682]
  [-2.2397666  -0.6480694 ]]], shape=(4, 3, 2), dtype=float32)
e:  tf.Tensor(
[[[-4.1455293   0.06467617]]

 [[ 2.446971   -2.3593805 ]]

 [[-0.20095806  0.5200487 ]]

 [[-3.1692467  -0.82145005]]], shape=(4, 1, 2), dtype=float32)
Shape:  (4, 1, 2)


In [ ]:
# Broadcasting batch matrix multiplication 
s = tf.random.normal(shape=[5,4,2,3])
t = tf.random.normal(shape=[5,4,3,1])
e = tf.einsum('...ij,...jk->...ik',s,t)
print("s: ",s)
print("\nt: ",t)
print("\ne: ",e)
print("Shape: ",e.shape)

s:  tf.Tensor(
[[[[-1.1331517   0.67617154  0.2225424 ]
   [-1.8830365   0.30079114  0.6541149 ]]

  [[-0.12679408  1.4166534  -2.205455  ]
   [ 1.039929    1.0424037   0.82712764]]

  [[-1.6045022   1.3605288  -0.7419855 ]
   [ 0.40414757 -0.6776483   0.82664335]]

  [[ 2.36031    -1.4425769   1.2536647 ]
   [ 1.1016114  -0.38294932 -0.17249477]]]


 [[[-0.08818439 -0.8078206  -0.2860677 ]
   [ 0.23859608  0.64554024  0.9976837 ]]

  [[ 0.03769297 -0.4813898  -0.9097077 ]
   [ 2.1258533  -0.68608993  1.232079  ]]

  [[ 0.47418126 -0.533622    0.08006232]
   [ 0.2800408   0.47423527 -1.3776412 ]]

  [[-0.1432205  -1.3870147   1.5837988 ]
   [ 0.62638354 -0.28669474  1.2091535 ]]]


 [[[-0.70820546  2.2528212  -0.7721183 ]
   [-1.2931587  -0.7578084  -0.15736277]]

  [[ 0.89067006  0.18728809  2.1126668 ]
   [ 0.38308275  0.11627229  0.7100349 ]]

  [[-0.36454874 -0.20402387 -0.91412705]
   [-0.3602542  -0.6500493   0.08505294]]

  [[ 0.2962495  -1.3857921   0.46606153]
   [-0.7703203  

## Tensorflow String

In [ ]:
# Tensors can be strings, too here is a scalar string. - 1D string
# b prefix indicates that tf.string dtype is not a unicode string, but a byte-string.
# tf.string is a dtype, which is to say you can represent data as strings (variable-length byte arrays) in tensors
scalar_string_tensor = tf.constant("Ashika Anand Babu")
print(scalar_string_tensor)

tf.Tensor(b'Ashika Anand Babu', shape=(), dtype=string)


In [ ]:
# Working with unicode:
s = tf.constant(u"Thanks 😊")
print(s)

tf.Tensor(b'Thanks \xf0\x9f\x98\x8a', shape=(), dtype=string)


Unicode Operations

In [ ]:
# LENGTH : Bytes, Characters

# Note that the final character takes up 4 bytes in UTF8.
thanks = u'Thanks 😊'.encode('UTF-8')
num_bytes = tf.strings.length(thanks).numpy()
num_chars = tf.strings.length(thanks, unit='UTF8_CHAR').numpy()
print('{} bytes; {} UTF-8 characters'.format(num_bytes, num_chars))

11 bytes; 8 UTF-8 characters


In [ ]:
# SUBSTRING

# Specifying unit='UTF8_CHAR', returns a single 4 byte character in this case
print(tf.strings.substr(thanks, pos=7, len=1, unit='UTF8_CHAR').numpy())

b'\xf0\x9f\x98\x8a'


In [ ]:
# SPLIT unicode string

print(tf.strings.unicode_split(thanks, 'UTF-8').numpy())

[b'T' b'h' b'a' b'n' b'k' b's' b' ' b'\xf0\x9f\x98\x8a']


In [ ]:
# MultiD string tensor
# If you have three string tensors of different lengths, this is OK.
tensor_of_strings = tf.constant(["Gray wolf",
                                 "Quick brown fox",
                                 "Lazy dog"])
# Note that the shape is (3,). The string length is not included.
print(tensor_of_strings)

tf.Tensor([b'Gray wolf' b'Quick brown fox' b'Lazy dog'], shape=(3,), dtype=string)


In [ ]:
# If you pass unicode characters they are utf-8 encoded.
tf.constant("😂🥳")

<tf.Tensor: shape=(), dtype=string, numpy=b'\xf0\x9f\x98\x82\xf0\x9f\xa5\xb3'>

In [ ]:
# You can use split to split a string into a set of tensors
print(tf.strings.split(scalar_string_tensor, sep=" "))

tf.Tensor([b'Ashika' b'Anand' b'Babu'], shape=(3,), dtype=string)


In [ ]:
# ...but it turns into a `RaggedTensor` if you split up a tensor of strings,
# as each string might be split into a different number of parts.
print(tf.strings.split(tensor_of_strings))

<tf.RaggedTensor [[b'Gray', b'wolf'], [b'Quick', b'brown', b'fox'], [b'Lazy', b'dog']]>
